# Generated by Django 4.1 on 2022-08-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person_myperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='MyPerson',
        ),
    ]
