# Generated by Django 4.1 on 2022-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
